import Link from "next/link";
import { Cards } from "@/data/data";
import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "Books | Diffrun",
  description: "Generated by create next app",
};

export default function Books() {
  return (
    <main className="w-full min-h-screen bg-gray-100 py-16 px-4 sm:px-6 lg:px-8">
      <div className="text-center mb-16">
        <p className="text-2xl sm:text-3xl font-semibold text-gray-800">
          Start crafting your one-of-a-kind story ✨
        </p>
      </div>

      <div className="grid gap-10 max-w-4xl mx-auto">
        {Cards.map((card, index) => (
          <div
            key={index}
            className="bg-white border border-gray-900 shadow-[8px_8px_0px_rgba(0,0,0,0.9)] rounded-none transition-transform duration-300 hover:-translate-y-1 hover:shadow-[10px_10px_0px_rgba(0,0,0,1)]"
          >
            <div className="flex flex-col md:flex-row">
              <div className="relative w-full md:w-96 h-72 md:h-auto overflow-hidden border-b md:border-b-0 md:border-r border-gray-300">
                <img
                  src={card.imageSrc}
                  alt={card.title}
                  className="object-cover w-full h-full transition-transform duration-300 hover:scale-105"
                />
              </div>

              <div className="flex flex-col justify-between flex-1 p-6 space-y-8">
                <div>

                  <h3 className="text-2xl font-semibold text-gray-900 mb-2">
                    {card.title}
                  </h3>
                  <p className="text-gray-700 text-base leading-relaxed">
                    {card.description}
                  </p>
                </div>

                <div className="mt-6">
                  <Link
                    href={`/child-details?job_type=story&book_id=${card.bookKey}`}
                  >
                    <button
                      className="w-full sm:w-auto bg-gradient-to-r from-indigo-500 via-purple-500 to-pink-500 text-white py-3 px-6 rounded-none font-medium border border-gray-900 shadow-[4px_4px_0px_rgba(0,0,0,0.9)] transition-transform duration-300 hover:-translate-y-1 hover:shadow-[6px_6px_0px_rgba(0,0,0,1)] focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-gray-950"
                    >
                      Personalize your book
                    </button>
                  </Link>
                </div>
              </div>
            </div>
          </div>
        ))}
      </div>
    </main>
  );
}